language: php
php:
  # using major version aliases

  # Alias de la version 5.2.17
  - "5.2"
  # Alias de la version 5.3.x
  - "5.3"
  # Alias de la version 5.4.x
  - "5.4"
  # Alias de la version 5.5.x
  - "5.5"
  # Alias de la version 5.6.x
  - "5.6"

  - hhvm

# Especificacion opcional de variables de entorno, por ejemplo para bases de datos
env:
#  - SYMFONY_VERSION="2.0.*" DB=mysql
#  - SYMFONY_VERSION="dev-master" DB=mysql
#  - DB=pgsql
#  - DB=mongodb
  - DB=mysql


# Ejecuta scripts antes de correr las pruebas, puede utilizar variables de entorno
before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# Configura notificaciones (email, IRC, campfire etc)
notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"
  email: "unix4you2@gmail.com"

# Lista de ramas que no sera tenidas en cuenta
branches:
  except:
    - MedidorDeVelocidad
    - gh-pages
    - HabilitacionAuditorias
    - AcordeonOpcionesCentrales

# Ramas del repositorio a tener en cuenta
branches:
  only:
    - master
# Mediante expresiones regulares
#    - /^deploy-.*$/
